# Week 4 Numpy



In [2]:
#load numpy
import numpy as np

#numpy function that takes a list an creates a numpy array
my_list = [1,2,3,4,5,6,7]

my_array = np.array(my_list)

my_array

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
#the numpy array has its own type

type(my_array)

numpy.ndarray

## Mathematic operations at scale with numpy

Lists are very convenient for storing information, but there aren't many easy ways to perform math on multiple elements of the list.

In [4]:
#create a new list containing the area of our 4 boxes

height = [1, 3, 4, 8]

length = [6, 5, 7, 2]

width = [8, 9, 1, 5]

areas = [0] * 4

areas[0] = height[0] * length[0] * width[0]

areas[1] = height[1] * length[1] * width[1]

areas[2] = height[2] * length[2] * width[2]

areas[3] = height[3] * length[3] * width[3]

areas

[48, 135, 28, 80]

In [5]:
#turn the lists into arrays and let numpy work its magic!

np_height = np.array(height)

np_length = np.array(length)

np_width = np.array(width)

areas = np_height * np_length * np_width

areas

array([ 48, 135,  28,  80])

## Different types mean different functionalities

While numpy arrays might seem very similar to lists, there are a few key differences between the two data structures

In [6]:
#cannot concatenate numpy arrays like lists

my_array + my_array

array([ 2,  4,  6,  8, 10, 12, 14])

In [7]:
#you must use the numpy function append

np.append(my_array, my_array)

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

In [8]:
#numpy arrays only contain one type

np.array([1,2,3,'ft'])

array(['1', '2', '3', 'ft'],
      dtype='<U21')

## Subsetting Numpy arrays

We can select elements in a numpy array just like a list, but we can select certain items in an array in a more elegant way now with numpy arrays.

In [9]:
my_array

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
#Like lists, we can select elements by index

my_array[0]

1

In [11]:
#Check each element of the array to see if it is true or false

my_array == 2

array([False,  True, False, False, False, False, False], dtype=bool)

In [12]:
#Subset the array by selecting all elements that are true

my_array[my_array > 2]

array([3, 4, 5, 6, 7])

## 2D Numpy arrays

Numpy can store data in two dimensional arrays, which are like columns and rows. We can use our square brackets to select values from our 2D array. Similar to what we will see with our pandas dataframes, we select rows then columns and we still have our zero based indexing.

In [13]:
my_2d_array = np.array([[1,2,3],[34,36,76],[8,45,33]])

my_2d_array

array([[ 1,  2,  3],
       [34, 36, 76],
       [ 8, 45, 33]])

In [14]:
#select the value on the second row and third column

my_2d_array[1][2]

76

In [15]:
#select the value on the first row and third column

my_2d_array[0,2]

3

In [16]:
#select the first row of data

my_2d_array[0,:]

array([1, 2, 3])

In [17]:
#select the first column of data

my_2d_array[:,0]

array([ 1, 34,  8])

In [19]:
#we can do operations column wise or row wise

my_2d_array.sum(axis = 1)

array([  6, 146,  86])

In [20]:
my_2d_array.sum(axis = 0)

array([ 43,  83, 112])