# Week 4 Questions

## Loading the package

In [36]:
#import numpy and give it an alias

import numpy as np

## Lists to numpy arrays

In [37]:
#create a list with 10 integers

my_list = [12, 34, 44, 43, 8, 65, 43, 92, 4, 100]

In [38]:
#convert that list into a numpy array and name it my_array

my_array = np.array(my_list)

my_array

array([ 12,  34,  44,  43,   8,  65,  43,  92,   4, 100])

In [40]:
#use the numpy function mean to find the average value of my_array

np.mean(my_array)

44.5

In [41]:
#use a method to find the average value of my_array

my_array.mean()

44.5

## Subsetting numpy arrays and numpy array operations

In [42]:
#select the first value of my_array

my_array[0]

12

In [44]:
#select the last 3 values of my_array

my_array[-3:]

array([ 92,   4, 100])

In [45]:
#create a numpy array with the values 23, 45, and 62 and save it as small_array

small_array = np.array([23, 45, 62])

small_array

array([23, 45, 62])

In [46]:
#append small_array to the end of my_array

np.append(my_array, small_array)

array([ 12,  34,  44,  43,   8,  65,  43,  92,   4, 100,  23,  45,  62])

In [48]:
#take the sum of small_array and add it to each element of my_array

np.sum(small_array) + my_array

array([142, 164, 174, 173, 138, 195, 173, 222, 134, 230])

## 2d numpy arrays


We are going to use a famous dataset in the world of python and data analysis; The Iris Dataset. This dataset has measurements about 3 different types of irises (Setosa, Veriscolor, and Virginica). Each row in these 2d arrays is a different flower and each column is a measurement of particular features of the flower. The columns are sepal length (cm), sepal width (cm), petal length (cm) and petal width (cm).

In [52]:
from sklearn import datasets

#load the dataset

iris = datasets.load_iris()

#select the rows that correspond to the different flower types

setosa = iris.data[0:50,:]

versicolor = iris.data[50:100,:]

virginica = iris.data[100:150,:]

In [53]:
#column names from left to right

iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [54]:
#print the contents of the setosa 2d numpy array

setosa

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [57]:
#what is the petal length of the flower on the 15th row?

setosa[14,2]

1.2

In [59]:
#print all of the measurements for the flower on the 43 row of the versicolor dataset

versicolor[42,:]

array([ 5.8,  2.6,  4. ,  1.2])

In [72]:
#what is the average petal width of the virginica irises?

np.mean(virginica[:,3])

2.0260000000000002

In [73]:
#what is the median value of sepal length of the versicolor irises?

np.median(versicolor[:,0])

5.9000000000000004

In [74]:
#do versicolor irises have larger petal lengths than virginica irises?

np.mean(versicolor[:,2]) > np.mean(virginica[:,2])

False

In [76]:
#what are their average values?

print('versicolor avg petal length (cm): ' + str(np.mean(versicolor[:,2])))

print('virginica avg petal length (cm): ' + str(np.mean(virginica[:,2])))

versicolor avg petal length (cm): 4.26
virginica avg petal length (cm): 5.552


In [80]:
#create a numpy array containing all the flowers

all_irises = np.concatenate((setosa,versicolor,virginica), axis = 0)

all_irises

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [88]:
# which feature is most correlated with sepal length?

# the numpy function corrcoef takes two np arrays and returns a correlation matrix

#print the correlation matrix betweeen sepal length and sepal width

np.corrcoef(all_irises[:,0], all_irises[:,1])

array([[ 1.        , -0.10936925],
       [-0.10936925,  1.        ]])

In [89]:
# print the correlation matrix betweeen sepal length and petal length

np.corrcoef(all_irises[:,0], all_irises[:,2])

array([[ 1.        ,  0.87175416],
       [ 0.87175416,  1.        ]])

In [90]:
#print the correlation matrix betweeen sepal length and petal width

np.corrcoef(all_irises[:,0], all_irises[:,3])

array([[ 1.        ,  0.81795363],
       [ 0.81795363,  1.        ]])