# Week 5 Control Flows

This week will take a look at control flows - The way we can make our code take twists and turns in the road. We will cover comparison operators, and/or operators, if then statements, and loops. These techniques will help us extend our programming capibilities by introducing complex logic to our scripts.

In [1]:
import numpy as np

## Comparison Operators - Equal to & not equal to

These statements can help us know whether or not one object is equal (or not equal) to another object. They are the simplest form of control flow and will be statement that allows our program to make decisions.

In [4]:
#define two simple variables

b = 4

c = 5

# is c equal to b?

c == b

False

In [5]:
# define a new variable that has the same value as b

a = 4

# is a equal to b?

a == b

True

In [6]:
# can work with the output of a function or calculation

type(c) == type(b)

True

In [7]:
# inequalities work very similarly

type(c) != type(b)

False

## Comparison Operators - Greater than or Less than

These follow the same pattern as equality statements, but they introduce more options for us.

In [8]:
# greater than

4 > 3

True

In [9]:
# less than

46 < 33

False

In [10]:
# greater than or equal to

38 >= 38

True

In [11]:
# less than or equal to

98 <= 12

False

## Comparison operators to subset data

As we have seen before, we can use these operators to make decisions (like selecting certain elements in an array)

In [12]:
#define an array of integers

my_array = np.array([3, 5, 2, 87, 45, 23, 3])

#select all elements in array that are equal to 3

my_array[my_array == 3]

array([3, 3])

In [13]:
# select all elements in array that are not equal to 3

my_array[my_array != 3]

array([ 5,  2, 87, 45, 23])

In [14]:
# select all elements in array that are greater than or equal to 13

my_array[my_array >= 13]

array([87, 45, 23])

## And & Or

The and operator will help us check to see if two conditions both meet our criteria. The or operator will help us check to see if at least one of two (or many) conditions are true.

In [15]:
# check if two conditions are both true

b = 4

c = 2

b > 2 and c > 2

False

In [16]:
# ampersand can be used in place of and

b > 2 & c > 2

False

In [17]:
# check if one of the two conditions is true

b > 2 or c > 2

True

In [18]:
# pipe can be used in place of or

b > 2 | c > 2

False

## If then statements

If then statements are a feature of programming that will take our equality statements and comparison operators and make complex decisions based on the criteria we lay out.

In [19]:
# simple if then statement

price = 4.99

#conditional statement

if price >= 3.00:

    #action to take if condition  is true (always indented by a tab)
    
    price_range = 'expensive'

In [20]:
price_range

'expensive'

In [21]:
#what happens if our condition is not met?

price = 1.99

if price >= 3.00:
    
    price_range_new = 'expensive'

In [22]:
price_range_new

NameError: name 'price_range_new' is not defined

In [25]:
# if else statement allows us to handle all other situations

price = 2.99

if price >= 3.00:
    
    price_range = 'expensive'

# else statement is indented at the same point as initial if statement

# it gets no condition, because it handles all other situations
    
else:
    
    price_range = 'cheap'

In [26]:
price_range

'cheap'

In [37]:
# if elif else statement will give us the tools for infinite complexity

price = 3.99

if price >= 2.00:
    
    price_range = 'mid-range'

elif price >= 3.00:
    
    price_range = 'expensive'
    
else:
    
    price_range = 'cheap'

In [38]:
price_range

'mid-range'

In [42]:
# nested if then statements

price = 2.99

size = 'large'

if price >= 3.00:
    
    if size == 'small':
        
        price_range = 'expensive'
        
    else:
        
        price_range = 'mid-range'

elif price >= 2.00:
    
    if size == 'small':
    
        price_range = 'mid-range'
        
    else:
        
        price_range = 'cheap'
    
else:
    
    price_range = 'cheap'

In [71]:
# using multi condition if statement requires ()

x = 3

y = 'ff'

if (x >= 3 and y == 'ff'):
    
    ans = True

else:
    
    ans = False

In [72]:
ans

True

## Loops

Loops are another type of control flow that will allow an operation to happen many many times in a row to accomplish a particular task. This can be helpful for particularly repetetive tasks and can allow our script to be written much more elegantly.

In [ ]:
#for loop

my_list = [1,2,3,4,5]

for i in my_list:
    
    print(i)

In [ ]:
for i in range(0,5):
    
    print(my_list[i])

In [ ]:
for i in range(0,5):
    
    my_list[i] = my_list[i] + 3
    
my_list

In [ ]:
counter = 12

for i in range(0,5):
    
    counter = counter + 1
    
    print(counter)

In [ ]:
#while loops

counter = 4

while counter > 1:
    
    counter = counter - 1
    
    print(counter)

In [ ]:
condition = False

counter = 0

while condition == False:
    
    counter = counter + 1
    
    if counter > 3:
        
        condition = True
        
    print(counter)

In [ ]:
condition = False

counter = 0

while condition == False:
    
    if counter > 3:
        
        condition = True
        
    counter = counter + 1
        
    print(counter)